name: build x86_64-pc-linux-gnu
on: [push]
jobs:
  x86_64-pc-linux-gnu:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++-14 git cmake liburing-dev libbtrfs-dev nodejs
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone ${{ github.server_url }}/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: mkdir -p debug-work
      - run: mkdir -p release-work
      - run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install/debug \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
            -S ${SHORT_SHA} -B debug-work && \
          cmake --build debug-work --parallel `nproc` && \
          cmake --install debug-work
      - run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 \
            -S ${SHORT_SHA} -B release-work && \
          cmake --build release-work --parallel `nproc` && \
          cmake --install release-work
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            install

